apiVersion: v1
kind: Secret
metadata:
  name: txpublisher-secret
  namespace: master
type: Opaque
stringData:
  config.yml: |
    postgres:
      host: postgresql.default.svc.cluster.local
      port: 5432
      user: postgres
      password: HW5V7u5Umd3UNTefnkbZCPB2JmpCPjUX
      dbname: cloud-final
      sslmode: disable
    redis:
      address: redis-master.default.svc.cluster.local:6379
      password:
      database: 0
    chain:
      node_url: wss://bsc-ws-node.nariox.org:443
      max_blocks_per_query: 100
    publisher:
      project_id: cloud-final-346107
      do_not_create_topic_if_missing: true
      enable_message_ordering: true
      delay_threshold: 1
