apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: master
  labels:
    app: api
  name: api
spec:
  # do not include replicas in the manifests if you want replicas to be controlled by HPA
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: us-west1-docker.pkg.dev/cloud-final-346107/cloud-final-services/api:master
          name: api
          ports:
            - containerPort: 8000
              name: http
          resources: 
            limits:
              cpu: 100m
              memory: 400Mi
          env:
            - name: SERVER_PORT
              value: "8000"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /app/credentials/credentials.json
          volumeMounts:
            - name: api-secret
              mountPath: "/app/config"
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: api-secret
          secret:
            secretName: api-secret
            items:
              - key: config.yml
                path: config.yml
        - name: gke-pod-default-service-account
          secret:
            secretName: gke-pod-default-service-account
            items:
              - key: credentials.json
                path: credentials.json
