apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: master
type: Opaque
stringData:
  config.yml: |
    server:
      port: 8000
    database:
      postgres:
        host: postgresql.default.svc.cluster.local
        port: 5432
        user: postgres
        password: HW5V7u5Umd3UNTefnkbZCPB2JmpCPjUX
        dbname: cloud-final
        sslmode: disable
      influxdb:
        url: http://influxdb2.default.svc.cluster.local
        token: bFeZIHHkLTURvFEUHAzEVt6cZ8oVy9Ab
        bucket: default
        organization: influxdata