apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
  namespace: master
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: api
