
name: Deploy service to GKE

on: 
  repository_dispatch:
    types: 
      - deploy-service

env:
  GKE_CLUSTER: autopilot-cluster-1
  GKE_ZONE: asia-southeast1
  NAMESPACE: ${{ github.event.client_payload.namespace }}
  SERVICE: ${{ github.event.client_payload.service }}

jobs:
  build:
    name: Setup, Build, and Publish Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/173159973736/locations/global/workloadIdentityPools/cloud-final-pool/providers/github-provider
          service_account: gke-account@cloud-final-346107.iam.gserviceaccount.com

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      # Rollout new updates
      - name: Apply and rollout
        run: |-
          kubectl apply -f ${{ env.NAMESPACE }}/${{ env.SERVICE }}/deployment.yml -n ${{ env.NAMESPACE }}
          kubectl rollout restart deployment/${{ env.SERVICE }} -n ${{ env.NAMESPACE }}
